.PHONY: clean All

All:
	@echo "----------Building project:[ dsAssignment3 - Debug ]----------"
	@cd "dsAssignment3" && "$(MAKE)" -f  "dsAssignment3.mk"
clean:
	@echo "----------Cleaning project:[ dsAssignment3 - Debug ]----------"
	@cd "dsAssignment3" && "$(MAKE)" -f  "dsAssignment3.mk" clean
